test: try integrating alerts
keymanapp/shared-sites pull request #40
Opened 2024-11-01 08:24 UTC by Meng-Heng

2024-11-04 06:39 UTC, mcdurdin requested changes
This looks really good. I have a few minor changes requested :grin:

2024-11-04 06:39 UTC, mcdurdin commented on _common/GFMAlerts.php
> +                return $block = array(
```suggestion
                return array(
```

I am not sure why you were assigning `$block` here?

2024-11-04 06:39 UTC, mcdurdin commented on _common/GFMAlerts.php
> +                $iconType .= $icon[$alertType] . $alertTitle; // return string
We should check for matches for $alertType in $icon. If there is no match, then we should return plain text for the block I think.

```
if(empty($icon[$alertType])) {
  return parent::blockQuote($block);
}
```

2024-11-04 06:39 UTC, mcdurdin commented on _common/GFMAlerts.php
> +        }
I don't think it is correct to return $e? It would be safer to eliminate the `try`/`catch` altogether and let errors bubble through

2024-11-04 06:39 UTC, mcdurdin commented on _common/GFMAlerts.php
> +            return parent::blockQuote($block);
It'd be better to put this in the if() block:

```
if(!preg_match('/^\>\s*\[\!(IMPORTANT|TIPS|NOTE|WARNING|CAUTION)\]\s(.*)/i', $block['text'], $matches)) {
  return parent::blockQuote($block);
}

$alertType = strtolower($matches[1]);
...
```

This way, it's easier to follow the code flow

2024-11-04 06:39 UTC, mcdurdin commented on _common/GFMAlerts.php
> +
We should add the standard Keyman header:

https://github.com/keymanapp/keyman/wiki/Keyman-Code-Style-Guide#file-header

2024-11-07 06:00 UTC, Meng-Heng commented
I have applied your suggestions @mcdurdin. It was not working on my localhost due to not running this command `composer dump-autoload`? That why it was taking a bit more time. Thank you for making the code more readable!

2024-11-08 01:42 UTC, mcdurdin approved these changes
LGTM. Good work!

2024-11-08 01:42 UTC, merged